const FETCH_WEATHER_PENDING='FETCH_WEATHER_PENDING';

const FETCH_CURRENT_SUCCESS='FETCH_CURRENT_SUCCESS';
const FETCH_FORECAST_SUCCESS='FETCH_FORECAST_SUCCESS';

const FETCH_WEATHER_ERROR='FETCH_WEATHER_ERROR';

const SET_CITY='SET_CITY';

export {
    FETCH_WEATHER_PENDING,
    FETCH_CURRENT_SUCCESS,
    FETCH_FORECAST_SUCCESS,
    FETCH_WEATHER_ERROR,
    SET_CITY   
}
